aList = NULL
try
	test()
catch
done
aList = :wow
? alist

func test
	test2()

func test2
	aList = [
		100,200,300,
		new point { m=[] error }
	]

class point x y z